### ISSUE TITLE
[UX] implementation status of the `--format`

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#30431]
This is an umbrella ticket for tracking the implementation status of the `--format` option.

- [X] docker events
- [x] docker history #30962 @TheHipbot 
- [X] docker images
- [X] docker info
- [X] docker inspect
- [X] docker ps
- [ ] docker search https://github.com/docker/docker/pull/31539 @TheHipbot 
- [X] docker stats

- [X] docker network ls
- [x] docker node ls #30424 @yongtang
- [x] docker node ps #28213 @yongtang
- [X] docker plugin ls
- [X] docker plugin inspect
- [x] docker secret ls https://github.com/docker/docker/pull/31552 @ripcurld0 
- [X] docker secret inspect
- [X] docker service inspect
- [x] docker service ls #28199 @yongtang
- [x] docker service ps #28213 @yongtang
- [x] docker stack ls https://github.com/docker/docker/pull/31557 @ripcurld0 
- [x] docker stack ps #28213 @yongtang
- [x] docker stack services #28199 @yongtang
- [x] docker system df https://github.com/docker/docker/pull/31482 @ripcurld0 
- [X] docker volume ls
- [X] docker volume inspect

For following commands, maybe worth adding `--format`, but either is fine.
- docker top (difficult because currently invoking external `top`)

For following commands, no need to implement the flag

:x: docker port https://github.com/docker/docker/pull/31859
:x: docker diff https://github.com/docker/docker/pull/31599 @ripcurld0  (PR for internally using formatter pkg has been merged)
:x: docker checkpoint ls https://github.com/docker/docker/pull/31800 @ripcurld0 (ditto)

cc @albers @sdurrheimer

**Comment by yongtang** [comment]
@AkihiroSuda `docker stack ps`, `docker node ps`, and `docker service ps` are being addressed in #28213 together; `docker stack service` and `docker service ls` are being addressed in #28199 together as well.

**Comment by AkihiroSuda** [comment]
thank you for the information, updated the list

**Comment by TheHipbot** [comment]
#dibs starting with history

**Comment by TheHipbot** [comment]
@AkihiroSuda I was hoping to get a code review before moving forward on other commands, here is the diff for the commit: https://github.com/TheHipbot/docker/commit/fb45ee07d1390850b65a8bbd0430ff51ce5db285. Also I was going to create an integration test for the new code, but running `make test-integration-cli` fails for me even on master with an error about the version. I will look in the docker-dev group but if you have any ideas please let me know. Thanks.

**Comment by thaJeztah** [comment]
@TheHipbot feel free to open as a pull request, then code review takes place on the pull request

**Comment by AkihiroSuda** [comment]
@TheHipbot 

I left some comments to your commit.

Probably additional integration test is not needed.

(`make test-integration-cli` doesn't work for you? )

**Comment by TheHipbot** [comment]
Submitted a pull request. And yes, when I run `make test-integration-cli` I get this error:

```
error: daemon at unix:///go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/docker.sock fails to 'docker version':
Client:
 Version:      1.14.0-dev
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   02e5b2301
 Built:        Mon Feb 13 01:33:23 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///go/src/github.com/docker/docker/bundles/1.14.0-dev/test-integration-cli/docker.sock. Is the docker daemon running?
---> Making bundle: .integration-daemon-stop (in bundles/1.14.0-dev/test-integration-cli)
make: *** [test-integration-cli] Error 1
```

I am running on a mac with the Docker version: 1.13.1-beta42

**Comment by AkihiroSuda** [comment]
I _guess_  `BINDDIR= make test-integration-cli` works for you
(Set BINDDIR to empty so that UNIX socket in the bundles dir works)

**Comment by TheHipbot** [comment]
I'm waiting for the PR to be merged for `docker history`. In the meantime I'll get started on `docker search`.

**Comment by ripcurld0** [comment]
@AkihiroSuda can you put #31482 next to `docker system df`
Thanks 🐪

**Comment by ripcurld0** [comment]
@AkihiroSuda - I am not sure why `docker checkpoint ls` needs format.
It has only one column (checkpoint name).
Are we going to add more attributes/columns to it?

Thanks.

**Comment by ripcurld0** [comment]
@AkihiroSuda I think I will also take `docker secret ls`. It won't take me that long, I have made some progress https://github.com/ripcurld0/docker/commit/99773bbb8ec36b26ea1f255905ace3cb5a3cfce1

**Comment by AkihiroSuda** [comment]
updated the list; moved `checkpoint ls` to the "either is fine" list
(I agree it is unneeded now, but maybe worth adding in future)

**Comment by ripcurld0** [comment]
@AkihiroSuda -- I have taken some initiative and added the format option to the followings:
* secret ls #31552 
* stack ls #31557 

Now I will pursue to checkpoint-ls, diff and  port.
Thanks.

**Comment by AkihiroSuda** [comment]
updated the list, thank you

**Comment by ripcurld0** [comment]
@AkihiroSuda you can check `docker diff`, `docker secret ls` and `docker checkpoint ls` check-boxes

**Comment by AkihiroSuda** [comment]
done

**Comment by AkihiroSuda** [comment]
docker search (#31539) is still left, but let me close this issue, as CLI is no longer part of this repo
