### ISSUE TITLE
Make Docker Service Logs GA

### ISSUE THREAD

**Issue by dperny** [moby/moby#31399]
This is a master issue for bring `docker service logs` to general availability. There is still work to do to bring them out of experimental. 

## P1s (Must Have for Release)
- [x] All Log Options
  - [x] Tail (#31500) 
  - [x] Since (#31500)
  - [ ] Details (blocked, see #31956)
- [x] Containers with TTYs (#31952)
- [ ] Verify support for non-JSON logging drivers (#28793)
- [x] Fix formatting (#31672)
- [ ] Update CLI/API reference

## P2s (Can Release Without)
- [x] Task logs (https://github.com/docker/docker/pull/29307)
- [ ] General API for arbitrary combinations of node/service/task logs
- [ ] Sorting logs

## Bugs (Can be worked on during code freezes)
- [x] Logs Hang on Service Restart (#31625)

Feel free to add or link issues here, and feel free to ping/assign me on any issues that seem to be errors or severe deficiencies in `docker service logs`.

**Comment by thaJeztah** [comment]
Task logs; see https://github.com/docker/docker/pull/29307

**Comment by srust** [comment]
I find `docker service logs` hangs if the log file is completely empty. Not sure if that is covered by the above issue list? For example, if the `docker service create` fails (invalid image specified) , or the command the service runs has no output, the `docker service logs` will hang. I can file a new issue if you'd prefer..

**Comment by dperny** [comment]
That's fixed in the latest master.

On Mar 8, 2017 6:34 PM, "Stephen Rust" <notifications@github.com> wrote:

I find docker service logs hangs if the log file is completely empty. Not
sure if that is covered by the above issue list? For example, if the docker
service create fails (invalid image specified) , or the command the service
runs has no output, the docker service logs will hang. I can file a new
issue if you'd prefer..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/31399#issuecomment-285236616>, or mute
the thread

**Comment by srust** [comment]
Ah thanks @dperny! Sorry, was only running latest release.. should have checked.

**Comment by dperny** [comment]
No problem. Let me know if for some reason it's still occurring on master.

**Comment by dperny** [comment]
This issue has outlived its usefulness so I think I'm gonna close it. @thaJeztah
