### ISSUE TITLE
[META] Splitting moby and docker

### ISSUE THREAD

**Issue by vieux** [moby/moby#32867]
See https://github.com/moby/moby/pull/32691 for context.

We want to split moby and docker, here is a *WIP* list of tasks.

- [ ] Use the new Docker CLI located at github.com/docker/cli https://github.com/moby/moby/pull/32694
- [ ] Add the Moby tool to moby/moby https://github.com/moby/moby/issues/32859
- [ ] Update references of dockerproject.org  https://github.com/moby/moby/issues/32860
- [ ] Create a place for async community communication https://github.com/moby/moby/issues/32861
- [ ] Setup a short url for go pkgs https://github.com/moby/moby/issues/32862
- [ ] Update contributing guidelines https://github.com/moby/moby/issues/32863
- [ ] Issues cleanup https://github.com/moby/moby/issues/32864
- [ ] Setup weekly reports https://github.com/moby/moby/issues/32865
- [ ] Update integration-cli tests https://github.com/moby/moby/issues/32866

Again the list is in progress, please use the comments to suggest any missing item.

**Comment by shykes** [comment]
Thanks @vieux great start,

Also:

- find a good an non-confusing home for the remaining monolith while we split it.

- split up the monolith

**Comment by shykes** [comment]
Also: define a plan for HTTP engine API.

**Comment by AkihiroSuda** [comment]
how to report security issues and who/how triages them

**Comment by vieux** [comment]
@shykes added your suggestions

@AkihiroSuda are you talking about the whole CVE process ?

**Comment by AkihiroSuda** [comment]
@vieux 

What I meant was that we would need equivalent of `security AT docker DOT com` (Or just reuse that address for Moby).
It would contain CVE process as well.

**Comment by mlaventure** [comment]
Does defining a plan for the HTTP engine API also include defining one for standard inter-component communication?

Also I created a project to more easily find the associated tasks (rather than having to bookmark this one): https://github.com/moby/moby/projects/6

**Comment by duglin** [comment]
While it might be nice for the component-level interactions, I'm more concerned with the API exposed to the user, so I would put the engine-like API at the top on the list and the other stuff in a "investigate" or "consider for later" category.

**Comment by dnephin** [comment]
@mlaventure I think inter-component communication is one of the bigger blockers for "split up the monolith" (https://github.com/moby/moby/issues/32872#issuecomment-297739935). It might make sense to track those blockers in that issue.

**Comment by mlaventure** [comment]
@duglin I agree that the engine API has priority, I was just wondering where the other one were tracked.

I'm fine with tracking them with #32872 as @dnephin suggested, it does make sense.

**Comment by thaJeztah** [comment]
@vieux I think a similar option to security@docker.com, but then for the moby project (e.g. security@mobyproject.org)

**Comment by rogersachan** [comment]
@vieux 
![image](https://cloud.githubusercontent.com/assets/7173984/25557355/af71adac-2cdd-11e7-805e-b8a7c4b0b1f6.png)

This is the image I got in my inbox regarding the docker split. It should be noted that docker still has ownership of swarmkit, infrakit, notary, distribution, libnetwork, and compose. Are these supposed to be transferred over to moby or will these actually become part of Docker CE/EE?

**Comment by shykes** [comment]
@rogersachan Moby does not aspire to "own" any other projects. We are using it as a temporary staging area for projects preparing to be spun-out as fully autonomous projects.

For the projects you list: we plan to spin these all out as standalone projects. They will neither be part of Moby nor Docker CE - but they will be upstream from both.

**Comment by rogersachan** [comment]
So swarmkit, infrakit, notary, distribution, libnetwork, vpnkit, datakit, hyperkit, and compose will all eventually be united from the moby and docker orgs? @shykes

**Comment by AkihiroSuda** [comment]
What should we do with `CHANGELOG.md`?

Do we want to just remove that file or keep maintaining that file (but without version)?
My opinion is the latter.

Also, do we want to deprecate weekly reports?
The moby project blog looks like the successor now.

**Comment by thaJeztah** [comment]
I suggested doing a weekly changelog (https://forums.mobyproject.org/t/proposal-create-weekly-change-logs/76), but possibly there will be weekly(?) releases. Starting with a fresh changelog would likely make sense though.

**Comment by AkihiroSuda** [comment]
Weekly changelog SGTM, but I think we are very likely to fail creating weekly changelogs unless the workflow is completely automated. 
So the first step might be extending poule :smile:

**Comment by thaJeztah** [comment]
Yes, I was playing with https://github.com/skywinder/github-changelog-generator/ a while back, but possibly the "release" code from containerd (https://github.com/containerd/containerd/tree/master/cmd/containerd-release) would work (or can be used as a starting point). Ideally, such a tool would take the `impact/xx` labels into account to group changes into categories.
