### ISSUE TITLE
containerd 1.0: runtime integration

### ISSUE THREAD

**Issue by mlaventure** [moby/moby#34662]
This is an issue to track the progress I'm making on integrating containerd 1.0 within the moby master.

I initially wanted to do a refactor and remove libcontainerd altogether while doing it, but decided to postpone so to a second pass to have it ready faster.

The branch I'm working of can be found [here](https://github.com/mlaventure/docker/tree/containerd-1.0). Be warned that I frequently force push to it and it is still full of extra debug code at the moment.

Currently, the following tests on linux (amd64):
 - Stats
   - [x] ~DockerSuite.TestAPIStatsContainerGetMemoryLimit~
   - [x] ~DockerSuite.TestAPIStatsContainerNotFound~
   - [x] ~DockerSuite.TestAPIStatsNetworkStats~
   - [x] ~DockerSuite.TestAPIStatsNetworkStatsVersioning~
   - [x] ~DockerSuite.TestAPIStatsNoStreamConnectedContainers~
   - [x] ~DockerSuite.TestAPIStatsNoStreamGetCpu~
   - [x] ~DockerSuite.TestContainerAPIStatsWithNetworkDisabled~
   - [x] ~DockerSuite.TestGetContainerStats~
   - [x] ~DockerSuite.TestGetContainerStatsNoStream~
   - [x] ~DockerSuite.TestGetContainerStatsRmRunning~
   - [x] ~DockerSuite.TestGetContainerStatsStream~
   - [x] ~DockerSuite.TestGetStoppedContainerStats~
   - [x] ~DockerSuite.TestStatsAllNoStream~
   - [x] ~DockerSuite.TestStatsAllRunningNoStream~
   - [x] ~DockerSuite.TestStatsContainerNotFound~
   - [x] ~DockerSuite.TestStatsFormatAll~
   - [x] ~DockerSuite.TestStatsNoStream~
 - Plugins
   - [x] ~DockerSuite.TestPluginUpgrade~
   - [x] ~DockerAuthzV2Suite.TestAuthZPluginAllowNonVolumeRequest~
   - [x] ~DockerAuthzV2Suite.TestAuthZPluginDisable~
   - [x] ~DockerAuthzV2Suite.TestAuthZPluginRejectVolumeRequests~
   - [x] ~DockerDaemonSuite.TestDaemonShutdownWithPlugins~
   - [x] ~DockerTrustSuite.TestPluginTrustedInstall~
 - Others
   - [x] ~DockerSuite.TestAPIIpcModeNone~
   - [x] ~DockerSuite.TestAPIIpcModeShareableAndContainer~
   - [X] ~DockerSuite.TestInfoAPIRuncCommit~
   - [x] ~DockerSuite.TestRunPIDHostWithChildIsKillable~
   - [x] ~DockerDaemonSuite.TestDaemonIpcModePrivate~
   - [x] ~DockerDaemonSuite.TestDaemonIpcModeShareable~
   - [x] ~DockerDaemonSuite.TestDaemonIpcModeShareableFromConfig~
   - [ ] DockerDaemonSuite.TestDaemonUserNamespaceRootSetting
   - [x] ~DockerDaemonSuite.TestExecWithUserAfterLiveRestore~
   - [x] ~DockerDaemonSuite.TestRunWithRuntimeFromCommandLine~
   - [x] ~DockerDaemonSuite.TestRunWithRuntimeFromConfigFile~
   - [x] ~DockerSuite.TearDownTest after TestExecResizeAPIHeightWidthNoInt (leading to 675 tests skipped and potentially failing  afterwards)~
   - [ ] Random deadlock observed on container creation, reproduction has been quite spotty

The following is yet to be tested:
  - [ ] arm
  - [ ] Windows

The following needs to be tests:
  - [ ] Checkpoint backward compatibility

Last run results (2017-09-06 18:00): `OOPS: 1664 passed, 82 skipped, 1 FAILED`
