### ISSUE TITLE
Proposal: containerd image integration

### ISSUE THREAD

**Issue by dmcgowan** [moby/moby#38043]
## Summary
Replace Moby image backend with containerd. This will move ownership of image related code outside of Moby allowing for a large code and scope reduction in Moby. Many refactorings can be done before doing the switch, but changing the backend can only be done in large increments due to the metadata storage architecture difference in containerd. 

### Overview
- Image storage moved to containerd metadata database
- Migration of existing metadata
- All image requests use containerd client
- Distribution code removed and replaced with containerd client
- Containerd’s snapshotters supported
- Graph drivers scoped down (no more mounting/diffing)
- Graph drivers supported as containerd snapshotter plugins

## Plan
This change is deep, in some cases we can completely bypass existing packages and use containerd (i.e. distribution), while in others we will need to write new code to integrate with existing Docker interfaces. There will likely be a few large PRs since Docker will not be able to be in a functional state unless the data storage is consistently used by all commands. This plan is an attempt to break down the work in individual PRs which can be merged in isolation while preserving as much functionality as possible. Some PRs may temporarily break upgrades since we will want to begin testing and integrating with some of these changes before the upgrade migration code is complete.

I have broken this down into phases to better understand the relationship between work items. There is no definition for the end of a phase but rather the work in each phase should be able to be completed concurrently.

### Phase 1
- libcontainerd simplification and windows runtime integration
- daemon updates
  - replace plugin executor interface with containerd client
  - replace image backend and distribution with containerd client
    - includes all image operations: ls, rm, pull, push, etc
    - unpack from content store into layer store
- minimizing graph driver scope
  - move mount to layer store and utilize containerd mount package
  - move diff to layer store and utilize containerd diff packages
### Phase 2
- move libcontainerd into daemon
- image metadata migration
  - support migrating existing docker metadata into containerd metadata store
- graph drivers updated to snapshotter interface
  - layer store communicating with containerd snapshotter
### Phase 3
- replace layer store with snapshotter
  - graph drivers exposed as containerd snapshotter plugins
  - support layer recreation into content store from tar split on push
- update storage driver configuration to reflect snapshotter preference

## Related PRs

 - [x] ~https://github.com/moby/moby/pull/37932~ https://github.com/moby/moby/pull/38168 Update containerd to 1.2x
 - [x] https://github.com/moby/moby/pull/37874 Remove the rest of v1 manifest support
   - [x] https://github.com/moby/moby/pull/39365 Keep but deprecate registry v2 schema1 logic and revert to libtrust-key-based engine ID
   - [ ] https://github.com/moby/moby/pull/39384 Remove v2 schema1 push
   - [ ] https://github.com/moby/moby/pull/39371 Remove more registry v1 code
 - [ ] https://github.com/moby/moby/pull/38738 Containerd image and snapshot backend integration

### Related project

https://github.com/dmcgowan/docker/projects/1 containerd-integration

**Comment by AkihiroSuda** [comment]
* Can we also allow specifying snapshotted per container, as in `ctr run --snapshot`?
* Are we ready to drop schema1 push? I'm not sure Quay supports schemae2/OCIv1 yet.

**Comment by dmcgowan** [comment]
> Can we also allow specifying snapshotted per container, as in ctr run --snapshot?

Yes, but out of scope for this proposal. I am not proposing any new functionality as part of this proposal, but this proposal does make many new functionality possible.

> Are we ready to drop schema1 push? I'm not sure Quay supports schemae2/OCIv1 yet.

Yes and also not sure. They have already already indicated they are working on it, we can make sure they are kept aware of the timeline here, but that discussion is happening in another issue.

**Comment by andrewhsu** [comment]
I propose we move the state of this issue from "proposal" to "yes we're doing this thing" if we have enough buy-in that this is for sure. (I think this is a desirable thing to do)

**Comment by nakabonne** [comment]
@andrewhsu @dmcgowan cc: @ajeetraina @dbjpanda
Hi, I’m Ryo Nakao, a student from Japan. I’m interested in this issue as a project idea of Google Summer of Code 2019. So I have two questions:

1. Is it alright that discussing about this idea here?
2. Where should I share the Google doc link once drafting is completed?

**Comment by nakabonne** [comment]
I heard that Docker withdrew the application earlier. I'm planning to contribute after the GSoC period is over, so thank you.

**Comment by Gesisfm** [comment]
> ## Summary
> Replace Moby image backend with containerd. This will move ownership of image related code outside of Moby allowing for a large code and scope reduction in Moby. Many refactorings can be done before doing the switch, but changing the backend can only be done in large increments due to the metadata storage architecture difference in containerd.
> 
> ### Overview
> * Image storage moved to containerd metadata database
> * Migration of existing metadata
> * All image requests use containerd client
> * Distribution code removed and replaced with containerd client
> * Containerd’s snapshotters supported
> * Graph drivers scoped down (no more mounting/diffing)
> * Graph drivers supported as containerd snapshotter plugins
> 
> ## Plan
> This change is deep, in some cases we can completely bypass existing packages and use containerd (i.e. distribution), while in others we will need to write new code to integrate with existing Docker interfaces. There will likely be a few large PRs since Docker will not be able to be in a functional state unless the data storage is consistently used by all commands. This plan is an attempt to break down the work in individual PRs which can be merged in isolation while preserving as much functionality as possible. Some PRs may temporarily break upgrades since we will want to begin testing and integrating with some of these changes before the upgrade migration code is complete.
> 
> I have broken this down into phases to better understand the relationship between work items. There is no definition for the end of a phase but rather the work in each phase should be able to be completed concurrently.
> 
> ### Phase 1
> * libcontainerd simplification and windows runtime integration
> * daemon updates
>   
>   * replace plugin executor interface with containerd client
>   * replace image backend and distribution with containerd client
>     
>     * includes all image operations: ls, rm, pull, push, etc
>     * unpack from content store into layer store
> * minimizing graph driver scope
>   
>   * move mount to layer store and utilize containerd mount package
>   * move diff to layer store and utilize containerd diff packages
> 
> ### Phase 2
> * move libcontainerd into daemon
> * image metadata migration
>   
>   * support migrating existing docker metadata into containerd metadata store
> * graph drivers updated to snapshotter interface
>   
>   * layer store communicating with containerd snapshotter
> 
> ### Phase 3
> * replace layer store with snapshotter
>   
>   * graph drivers exposed as containerd snapshotter plugins
>   * support layer recreation into content store from tar split on push
> * update storage driver configuration to reflect snapshotter preference
> 
> ## Related PRs
> * [x]  ~[[wip] Update containerd runtime to v1.2.0 #37932](https://github.com/moby/moby/pull/37932)~ [Update containerd to 1.2x #38168](https://github.com/moby/moby/pull/38168) Update containerd to 1.2x
> * [x]  [Remove the rest of v1 manifest support #37874](https://github.com/moby/moby/pull/37874) Remove the rest of v1 manifest support
>   
>   * [x]  [Keep but deprecate registry v2 schema1 logic and revert to libtrust-key-based engine ID #39365](https://github.com/moby/moby/pull/39365) Keep but deprecate registry v2 schema1 logic and revert to libtrust-key-based engine ID
>   * [ ]  [Remove v2 schema1 push #39384](https://github.com/moby/moby/pull/39384) Remove v2 schema1 push
>   * [ ]  [Remove more registry v1 code #39371](https://github.com/moby/moby/pull/39371) Remove more registry v1 code
> * [ ]  [Containerd image and snapshot backend integration #38738](https://github.com/moby/moby/pull/38738) Containerd image and snapshot backend integration
> 
> ### Related project
> https://github.com/dmcgowan/docker/projects/1 containerd-integration

**Comment by ousiax** [comment]
It seems that this issue or feature is pending now?

**Comment by AkihiroSuda** [comment]
Experimentally implemented in v24:
https://github.com/moby/moby/blob/cf15460a3b9d23334fcc063ff1396844b16fa11d/daemon/daemon.go#L825

Remaining issues are tracked in https://github.com/moby/moby/labels/containerd-integration
