### ISSUE TITLE
LCOW greener pastures

### ISSUE THREAD

**Issue by andrewhsu** [moby/moby#39533]
Looks like Linux Container on Windows (LCOW) work in moby codebase has a sizable gap to fill to achieve its desired functionality in a way that could take it out of `experimental` status. There are things that [barely work or do not work at all](https://github.com/moby/moby/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aarea%2Flcow+). Unless I'm missing something, I do not see how the initial implementation of LCOW could eventually complete or if it is still desirable to pursue the initial implementation strategy. I suggest we send the LCOW code changes to live on in the memory of git history and close issues related to LCOW.

reference: #33850 #34617

Related pull requests:

- [x] https://github.com/docker/cli/pull/2798
- [x] https://github.com/moby/moby/pull/42451
- [x] https://github.com/moby/moby/pull/42499
- [x] https://github.com/moby/moby/pull/42506
- [x] https://github.com/moby/moby/pull/42511
- [x] https://github.com/moby/moby/pull/42517
- [x] https://github.com/moby/moby/pull/42520
- [x] https://github.com/moby/moby/pull/42683
- [x] https://github.com/moby/moby/pull/42684
- [x] https://github.com/moby/moby/pull/42685
- [x] https://github.com/moby/moby/pull/43362
- [x] https://github.com/docker/cli/pull/3451 
- [x] https://github.com/docker/cli/pull/3223
- [ ] (remaining bits) https://github.com/moby/moby/pull/42170

**Comment by Iristyle** [comment]
I'm having a difficult time understanding the long-term plan / strategy here, so hopefully Docker / Microsoft can provide some clarification on the direction of Linux container support on Windows (side-by-side with Windows containers). I've tried to follow issue trackers / announcements closely across a number of repos (https://github.com/linuxkit/lcow, https://github.com/docker/libnetwork, https://github.com/microsoft/hcsshim, https://github.com/microsoft/opengcs, https://github.com/docker/for-win, moby, etc) and blog posts, but the communication from both companies and confusing naming has made it very difficult as a consumer / implementor to understand where this is ultimately going. I thought all paths ultimately led to LCOW, so seeing this ticket here is unexpected.

From a really high level, these are the major directional changes I've seen:

- Initial Linux container support in "Linux mode" running on top of the MobyLinux VM. This is a fatter VM for running Linux containers and they *cannot* be run concurrently with Windows containers... but many Linux containers initially worked there (i.e. Postgres) because Linux containers were all hosted in a Linux VM that was effectively unaware that it was run inside Windows.

- LCOW is introduced as the future of the platform as it allows Linux and Windows containers to run side by side (presumably heterogenous workloads are the big differentiator on Windows). Notably, some of the isolation mode details have been changed, the kernel image more directly integrates with the hyper-v compute layer, and the file system mapping was reimplemented on top of the 9P protocol, allowing host NTFS volumes to map into Linux file system volumes (sharing code with WSL from what I understand). This initially broke a lot of previously working containers (i.e. Postgres) - but eventually containers that had difficulty running (i.e. Postgres) could run without crashing on RS5.

- LCOW v2 - Internal changes to [run on top of containerd that require newer Hyper-V APIs present in Windows Build RS5](https://github.com/moby/moby/issues/33850#issuecomment-478192332). LCOW v1 was effectively deprecated, and most new features (or fixes for broken features) I expected would land here. The signal I got from this was an updated vision of the future of Linux Containers on Windows that required core OS support.

- WSL 2 - Docker is now [actively promoting](https://github.com/moby/moby/issues/33850#issuecomment-519493489) this method, so it's very unclear what this means for LCOW, especially given this moby project issue.  I understand the reason for moving away from MobyLinux VM in the Docker desktop packages, but I really don't understand the shift to WSL 2 instead of using LCOW? Please correct me if I'm wrong, but my understanding is that WSL2 uses a kernel image thats similar to / provided by the LinuxKit / LCOW team, so some of the underpinnings are the same. I also saw a comment that this still doesn't allow side-by-side Windows / Linux containers -- so it would be helpful to understand the technical justifications / ramifications of this latest different approach.


I should note that the way these various bits are packaged up into installers also muddies the waters quite a bit. For our usage over the last year, we've not installed packages and have basically:

* Turned on Hyper-V and container support in Windows
* Grabbed nightly Windows docker builds and set them to run as a service
* Installed compose from GitHub releases
* Turned on experimental features to enable LCOW
* Dropped the latest LCOW kernel image / init filesystem in the appropriate place

So any clarity around this would be great to hear! Thanks!

**Comment by thaJeztah** [comment]
Update from Microsoft on https://github.com/moby/moby/issues/33850#issuecomment-591180956

> Linux Containers on Windows development moved to [ContainerD](https://github.com/containerd/containerd), and no more work is happening in the Moby codebase. I don't think we need to keep this epic open any longer since there's no progress tracked here.

**Comment by AkihiroSuda** [comment]
We should have LCOW deprecation notice in https://github.com/docker/cli/blob/master/docs/deprecated.md ?

**Comment by olljanat** [comment]
@AkihiroSuda most probably yes and iiuc that should added there already now before 20.03 release. Other why #41455 will be much harder to implement.

**Comment by olljanat** [comment]
> Update from Microsoft on [#33850 (comment)](https://github.com/moby/moby/issues/33850#issuecomment-591180956)
> 
> > Linux Containers on Windows development moved to [ContainerD](https://github.com/containerd/containerd), and no more work is happening in the Moby codebase. I don't think we need to keep this epic open any longer since there's no progress tracked here.

@thaJeztah I assume that it means that we can also remove those LCOW references from Windows CI scripts? Afaiu those are not included to CI currently. And I think that also with than one we should remove integration tests on container logic which have not ever worked as because of limitation on Windows. That would allow us remove quite a lot of if/else logic...

**Comment by thaJeztah** [comment]
> We should have LCOW deprecation notice in https://github.com/docker/cli/blob/master/docs/deprecated.md ?

Yes, that would make sense. I think I had a branch with that somewhere, but it was pending approval and I may have removed it 🤔


So we had an internal discussion some time back about LCOW; one of the reasons for that discussion was that there were still (some) uses at Microsoft (or customers from Microsoft; don't have details). Following that discussion we decided to start deprecating LCOW, but not heavily invest resources in _removing_ the code. 

First step was to add a build-flag to allow disabling LCOW (https://github.com/moby/moby/pull/40766). Docker Desktop (final timing to be discussed, possibly with the 20.xx release) will disable LCOW. Motivation behind that was that we want to focus on WSL2 on Docker Desktop, which provided a better experience than LCOW, which has too many limitations/bugs, and caused confusion for users that (accidentally) switched to "Windows containers", and then started Linux containers (ending up with LCOW, and its limitations).

As to _removing_ the code; I propose to keep the code in until we cut the 20.xx branch, after which we can start cleaning up LCOW code that's no longer needed.

That said, we should take care with removing if LCOW will be revived with the containerd implementation (as in: there may be parts in the codebase that would still be needed there? I haven't looked into that).

**Comment by olljanat** [comment]
> That said, we should take care with removing if LCOW will be revived with the containerd implementation (as in: there may be parts in the codebase that would still be needed there? I haven't looked into that).

Afaiu idea is that containerd + hcsshim combination handles whole LCOW/WCOW dilemma so Docker can just request containerd to create container with specified specs. Look example from https://github.com/microsoft/hcsshim/blob/master/test/cri-containerd/runpodsandbox_test.go how they are testing different combinations.

**Comment by thaJeztah** [comment]
Yes, mostly thinking about weird corner-cases (path conversions for bind-mounts, perhaps which image to pull for multi-arch manifests)

**Comment by olljanat** [comment]
On quick look those actually looks to be handled nicely (at least on tests) as most of mount and volume parsing run on both Linux and Windows and even those LCOW specific cases run also on WCOW too. I was not able to find any LCOW specific integration tests from here.

**Comment by thaJeztah** [comment]
Closing this ticket, as LCOW has been removed in Docker 23.0 and up (https://github.com/docker/cli/pull/3223). There are some small left-over bits remaining (https://github.com/moby/moby/pull/42170) but not worth tracking here.
