### ISSUE TITLE
[epic] stop using old (release) branches and unify API docs

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#40342]
I noticed that we still have some old release branches in this repository. Some of those branches have changes that never made it into a release (or documentation cherry-picks that were published in the documentation, but not tagged as a release)

Branch                                               | Changes not in a release
-----------------------------------------------------|--------------------------------------------------------------
[1.12.x](https://github.com/moby/moby/tree/1.12.x)   | https://github.com/moby/moby/compare/v1.12.6...1.12.x
[1.13.x](https://github.com/moby/moby/tree/1.13.x)   | https://github.com/moby/moby/compare/v1.13.1...1.13.x
[17.03.x](https://github.com/moby/moby/tree/17.03.x) | https://github.com/moby/moby/compare/v17.03.2-ce...17.03.x
[17.04.x](https://github.com/moby/moby/tree/17.04.x) | https://github.com/moby/moby/compare/v17.04.0-ce...17.04.x
[17.05.x](https://github.com/moby/moby/tree/17.05.x) | https://github.com/moby/moby/compare/v17.05.0-ce...17.05.x (no diff)
[docs](https://github.com/moby/moby/tree/docs)       | documentation-only changes

Some care should be taken when removing these branches, because the docker documentation fetches some resources from some of these branches; https://github.com/docker/docker.github.io/blob/ec57364ede82a135021e2e762bd0833d92a0cc0f/_scripts/fetch-upstream-resources.sh#L74 https://github.com/docker/docker.github.io/blob/ec57364ede82a135021e2e762bd0833d92a0cc0f/_scripts/fetch-upstream-resources.sh#L89-L95

In addition, with the introduction of the Swagger file (which is used to document current versions of the API), this repository only has a definition of the _current_ version of the API. Older versions of the API need to be fetched from either tags in various repositories, or from release-branches in those repositories. Having those files spread in various locations makes building the docs complicated, but also makes it more difficult to _compare_ changes between API versions, or to make fixes to the API documentation (if there's a bug or missing documentation in existing API versions).

I'm planning to add copies of the swagger.yml for each API version. in this repository to address that.

- [x] update docker-ce-packaging to build from upstream repositories instead of the mono-repo; https://github.com/docker/docker-ce-packaging/pull/449
    - note: more changes needed in the private release packaging repositories, but those are tracked separately
- [x] update fetch-upstream-resources.sh script in documentation repository to not depend on these branches (https://github.com/docker/docker.github.io/pull/10101)
    - [x] https://github.com/docker/docker.github.io/pull/10343 Engine API: use template for API reference pages
    - [x] https://github.com/docker/docker.github.io/pull/10348 Simplify use of "ENGINE_BRANCH" and "DISTRIBUTION_BRANCH"
    - [x] https://github.com/docker/docker.github.io/pull/10344 [WIP] simplify fetching API versions
    - [x] https://github.com/docker/docker.github.io/pull/10578 Engine API: remove per-branch fetching of API docs
- [x] backport fetch-upstream-resources.sh changes to documentation archive branches
    - [x] v18.09 archive branch https://github.com/docker/docker.github.io/pull/10196
    - [x] v18.03 archive branch https://github.com/docker/docker.github.io/pull/10349
    - [x] ~v17.12 archive branch~ won't fix
    - [x] ~v17.09 archive branch~ won't fix
    - [x] ~v17.06 archive branch~ won't fix
    - [x] ~v17.03 archive branch~ won't fix
    - [x] ~v1.13 archive branch~ won't fix
- [x] add a copy of the swagger.yml for each released version of the API
    - [x] v1.40 - docker v19.03 https://github.com/moby/moby/pull/40570 
    - [x] v1.39 - docker v18.09 https://github.com/moby/moby/pull/40570 
    - [x] v1.38 - docker v18.06 https://github.com/moby/moby/pull/40570 
    - [x] v1.37 - docker v18.03 - v18.05 https://github.com/moby/moby/pull/40778
    - [x] v1.36 - docker v18.02 https://github.com/moby/moby/pull/40778
    - [x] v1.35 - docker v17.12 - v18.01 https://github.com/moby/moby/pull/40778
    - [x] v1.34 - docker v17.11 https://github.com/moby/moby/pull/40778
    - [x] v1.33 - docker v17.10 https://github.com/moby/moby/pull/40778
    - [x] v1.32 - docker v17.09 https://github.com/moby/moby/pull/40778
    - [x] v1.31 - docker v17.07 https://github.com/moby/moby/pull/40778
    - [x] v1.30 - docker v17.06 https://github.com/moby/moby/pull/40778
    - [x] v1.29 - docker v17.05 https://github.com/moby/moby/pull/40570 
    - [x] v1.28 - docker v17.04 https://github.com/moby/moby/pull/40570 
    - [x] v1.27 - docker v17.03 https://github.com/moby/moby/pull/40570 
    - [x] v1.26 - docker v1.13.1 https://github.com/moby/moby/pull/40570 
    - [x] v1.25 - docker v1.13.0 https://github.com/moby/moby/pull/40570 
- [x] cherry-pick copy of swagger.yaml to current release branch
    - [x] https://github.com/moby/moby/pull/40575 [19.03 backport] docs: add API versions v1.25 - v1.29, v1.38 - v1.40
    - [x] https://github.com/moby/moby/pull/40779 [19.03 backport] docs: add API versions v1.30 - v1.37
- [x] ~remove unused release-branches~ we can't update all archives, so we may want to keep the old branches (but eventually, "archive" the docker/docker-ce repository once it's no longer used in the build pipeline

**Comment by AkihiroSuda** [comment]
Why do you want to remove the old branches? Is this related to go mod issue?

**Comment by thaJeztah** [comment]
> Why do you want to remove the old branches? Is this related to go mod issue?

A bit of a combination;

- these old branches are not actively maintained, so if possible, I'd like to clean up those repositories. It's already confusing/messy with all the repositories that exist, so trying to reduce clutter. Also, tags are a slightly more "format" contract to exist, whereas branches are more likely to be removed (accidentally), so I'd like to not rely on them if there's no need.
- I'm working with @silvin-lubecki to see if we can simplify both our release process, and the "repository mess"; part of that is unifying all tags. Right now, there's tags that can be found in `moby/moby` (and `docker/engine`) for _some_ releases, whereas for other releases, tags only exist in `docker/docker-ce`. For those tags (tags that are only in `docker/docker-ce`) we won't be able to get the same _sha_ in `docker/engine` (and `docker/cli`) due to the docker-ce repository using a different structure (it's a mono-repo with CLI and Engine being in the `components/` subdirectory), but at least we should be able to get tags that have the exact same _content_
- Once that's done (and if the maintainers are ok with it), we can bring those tags into this (moby/moby) repository as well (related to https://github.com/moby/moby/issues/40235).

While the above won't _fix_ the `go mod` situation (or "vendoring" / "dependency" in general), it _would_ make everything slightly less confusing.

**Comment by thaJeztah** [comment]
Looking at what's needed; I don't think we can easily _remove_ the old release branches; there's still too many locations where they're referenced (e.g. archived docs branches). As is being discussed in some place, we will continue the work to remove the "docker/docker-ce" from our build-pipeline, and may in future archive that repository (but not _remove_ it).

**Comment by thaJeztah** [comment]
Work is in progress to extract tags from the docker/docker-ce repository and to add them to the moby/moby repo. Due to the docker/docker-ce repo using a different directory layout (it's a mono-repo that contains upstream source as "components", that _will_ mean that the commit-hashes won't match, but the _code_ should be the same. Here's a "gist" with some results so far (validation scripts are being worked on); https://gist.github.com/silvin-lubecki/67f5099d6b4b2d0e055fd35d7137cf4c

**Comment by tao12345666333** [comment]
The `Git commit` field in `docker version`'s output is the commit id in `docker/docker-ce` ?

```
Server: Docker Engine - Community
 Engine:
  Version:          0.0.0-20200222012722-f4969a168f
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       f4969a168f
  Built:            Mon Feb 24 20:11:09 2020
  OS/Arch:          linux/amd64
  Experimental:     true

```

**Comment by thaJeztah** [comment]
Once we remove docker/docker-ce from the pipeline, the version output will show the commits from the moby and cli repositories individually (so they won't be the same for the cli and daemon), which makes more sense as they're different code bases, and also are separate packages nowadays (just released at the same time).

**Comment by thaJeztah** [comment]
I'll close this ticket, as most of the work is done; there's still some internal repositories that need updates, but tracking those internally
