### ISSUE TITLE
cgroup2 check list

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#40360]
- [X] base: https://github.com/moby/moby/pull/40174
- [x] metrics (`docker stats`): https://github.com/moby/moby/pull/40657
- ~~disable cgroupns for privileged containers? (https://github.com/kubernetes/enhancements/pull/1370)~~ (Probably not needed for Moby : https://github.com/containers/libpod/issues/5341)
- [x] systemd cgroup driver for rootless mode: https://github.com/moby/moby/pull/40486
- [x] use "systemd" cgroup driver by default when available : https://github.com/moby/moby/pull/40846
- [ ] CI (rootful): https://github.com/moby/moby/pull/41065 https://github.com/moby/moby/issues/41218
    - [ ] add stage to Jenkinsfile, running a distro with cgroups v2 (e.g. 19.10 (kernel 5.3) with `systemd.unified_cgroup_hierarchy=1` enabled)
    - [ ] override (?) containerd and runc binary versions (`CONTAINERD_COMMIT`, `RUNC_COMMIT`)  (related: https://github.com/moby/moby/pull/40094)
    - [ ] ??
- [ ] CI (rootful+systemd)
   - [x] Add systemd to the integration testing image? (PR: https://github.com/moby/moby/pull/40493)
- [ ] CI (rootless+systemd)

- [ ] docs: https://github.com/docker/docker.github.io/pull/11042

Low hanging fruits:
- [x] Put cgroup version to `docker info`: https://github.com/moby/moby/pull/40662
-  ~`dockerd --cpu-rt-{period,runtime}`~ (Can't be supported)

related: https://github.com/containerd/containerd/issues/3726 https://github.com/opencontainers/runc/issues/2209

**Comment by thaJeztah** [comment]
From slack conversation with @StefanScherer :

> I've added the Ubuntu 19.10 machine, you can use label `ubuntu-1910`  or `ubuntu-1910-overlay2` to select this os version. Kernel parameter is set.

So, we can work on having CI running (I'll clean up https://github.com/moby/moby/pull/40094, and see if I can use that as base, as we may need custom containerd/runc versions for testing)

**Comment by AkihiroSuda** [comment]
Keeping this issue open seems to have caused confusion that as if cgroup2 isn't supported yet, so I'm closing this one.

What we really still lack is just CI infra for cgroup2

**Comment by AkihiroSuda** [comment]
To people who came here: cgroup2 is supported when you run Docker 20 + containers 1.4 + runc 1.0-rc91.

Docker 20 isn't officially released yet, and its ETA is still unpublished

**Comment by cwhuang** [comment]
Hi, I've succeeded to install docker 20.10.0-rc2 by the above method.
# dockerd -v
Docker version 20.10.0-rc2, build ca520bd

However, I still encountered the cgroup issue:
ERRO[2020-12-03T07:56:40.528810125Z] Handler for POST /v1.41/containers/7279876e003f70939afc4b286b0379777355f270be7d801a65d350a49900e9f9/start returned error: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: open /sys/fs/cgroup/cpuset/docker/cpuset.cpus: no such file or directory: unknown

What's wrong? Do I need any config to tell dockerd to use cgroup2? Thanks!

**Comment by AkihiroSuda** [comment]
@cwhuang Please fulfill https://github.com/moby/moby/blob/master/.github/ISSUE_TEMPLATE.md and open a new issue
