### ISSUE TITLE
Proposal: deprecated (and remove) "--cluster-xx" options (legacy overlay networks)

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#40383]
The "node discovery" feature was added to implement overlay networks with an external k/v store
https://docs.docker.com/engine/reference/commandline/dockerd/#node-discovery

With swarm "standalone" being in maintenance mode, and SwarmKit providing all functionality to create overlay networks (which could be used for standalone swarm if created with the `--attachable` option), we should deprecate this feature, and remove it.

- [x] deprecate/remove `--cluster-advertise`, `--cluster-store `, `--cluster-store-opt` flags from `dockerd` CLI
    - [x] remove options from libnetwork https://github.com/moby/libnetwork/pull/2521 
    - [x] vendor libnetwork changes and remove local discovery packages https://github.com/moby/moby/pull/42247
    - [x] https://github.com/docker/cli/pull/2448 Deprecate classic Swarm and overlay networks using external k/v stores
    - [x] hide/deprecate flags and print warning https://github.com/moby/moby/pull/40510 "Deprecate '--cluster-xx' options and add warning"
    - [x] Add warnings for deprecated "cluster" functions, and deprecate API fields https://github.com/moby/moby/pull/40614
        - Add warning about deprecated "cluster" options to "docker info"
        - API: deprecate /info "ClusterStore" and "ClusterAdvertise" fields
    - [x] remove equivalent options from `daemon.json` (or produce error)
- [x] update reference docs
    - [x] remove flags from [`dockerd` command line reference](https://github.com/docker/cli/blob/86281a7b4b956446fe9a0f33b59a7defa9b3cb27/docs/reference/commandline/dockerd.md)
    - [x] remove flags from [`dockerd (8)` man page](https://github.com/docker/cli/blob/master/86281a7b4b956446fe9a0f33b59a7defa9b3cb27/dockerd.8.md)
- [x] Remove the [Overlay networking with an external key-value store](https://github.com/docker/docker.github.io/blob/a8e84a80e1b9968b55d3487bbfef0a98bcd5c5a4/network/overlay-standalone.swarm.md) documentation

The following flags will be removed/deprecated on the `dockerd` daemon:

```
      --cluster-advertise string                Address or interface name to advertise
      --cluster-store string                    URL of the distributed storage backend
      --cluster-store-opt map                   Set cluster store options (default map[])
```

(this is just a placeholder to start the discussion, I'll add more information about things to change)

**Comment by dontub** [comment]
We are currenlty using etcd for overlay networks. Is there some recommended approach on how to migrate to Swarm?

**Comment by thaJeztah** [comment]
> We are currenlty using etcd for overlay networks. Is there some recommended approach on how to migrate to Swarm?

It's possible to use swarm overlay network without using swarm services;

- enable swarm (`docker swarm init` to initialize a manager, and `docker swarm join` to join manager and worker nodes)
- when creating an overlay network, use the `--attachable` option, which allows non-swarmkit containers to join the network, e.g.

```
docker network create --driver=overlay --scope=swarm --attachable myoverlaynetwork
```

**Comment by dontub** [comment]
Actually what I meant was the process of dropping the `--cluster-xx` options, re-creating the networks, and re-connecting the containers. I've tried it now myself. What works is:
- (No disconnect from or deletion of overlay networks)
- Start docker without `--cluster-xx` options
- `docker swarm init`
- Create overlay network(s)
- Connect containers (containers cannot be started before: `Could not attach to network  <ID>`)

The following shell script can be used to do this:
```
OVERLAY_NETWORKS=" network1 network2 "

docker swarm init

for network in $OVERLAY_NETWORKS; do
  docker network create -d overlay --attachable $network
done

for container in $(docker ps -a --format '{{.Names}}'); do
  for network in $(docker inspect --format='{{range $name, $conf := .NetworkSettings.Networks}}{{$name}}{{" "}}{{end}}' $container); do
    if [[ "$OVERLAY_NETWORKS" = *" $network "* ]]; then
      echo Connect $container to network $network
      docker network connect $network $container
    fi    
  done
done
```
