### ISSUE TITLE
rootless: graduate from experimental

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/moby#40484]
Major remaining tasks towards graduation:
- [x] Add fuse-overlayfs storage driver (PR: https://github.com/moby/moby/pull/40483)
- [x] Support cgroup with cgroup v2+systemd driver (Issue: https://github.com/moby/moby/issues/40360, PR: https://github.com/moby/moby/pull/40486)
- [x] CI for `test-integration` w/o `testutil/daemon` (PR: https://github.com/moby/moby/pull/40538)
- [x] CI for `test-integration` w/ `testutil/daemon`  (PR: https://github.com/moby/moby/pull/40689)

Non-blocker:
- [ ] CI for `test-integration-cli`
- [ ] Consider reimplementing installer (issue https://github.com/docker/docker-install/issues/163)

**Note**: [Red Hat moved Rootless Podman out of "Technology Previews" in RHEL 8.1](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.1_release_notes/index#notable_changes_to_containers), with**out** supporting cgroup.

So maybe we can declare Moby's graduation from experimental without supporting cgroup as well.

**Comment by cpuguy83** [comment]
In my mind the purpose of experimental is to allow us to try out API's/interfaces that we are allowed to break as needed. This gives us time to ensure those interfaces by allowing users to try them out and give feedback.

Are we at the point where we don't need to make breaking changes for rootless? If so, then 💯 let's move it out.
I don't think it has to be fully optimized or fully featured to be supported so long as future optimizations or feature additions do not require breaking changes.

**Comment by AkihiroSuda** [comment]
I think we don't need any breaking change.

**Comment by thaJeztah** [comment]
I think we could consider removing the requirement to have "experimental" enabled, but make sure that we still list limitations that are in place (I think we did the same for user namespaces: we didn't require "experimental", but still kept some notes as to what people could expect, and what things would be improved in future).

Related to this: IIUC, the "rootless-install" script currently relies on nightly builds, but we did backport various changes to 19.03; are there things remaining for which we _require_ the nightly builds, or should we update the script to install "19.03"?

@AkihiroSuda related to the above; I seem to recall there were some binaries not included in the default (19.03) builds. Are changes needed in packaging to make the above work?

**Comment by AkihiroSuda** [comment]
> should we update the script to install "19.03"?

Already done. https://github.com/docker/docker-install/pull/146

>  I seem to recall there were some binaries not included in the default (19.03) builds. Are changes needed in packaging to make the above work?

slirp4netns is not included (even on master) because there was a (IIUC non-legal) concern in distributing a GPL 2 binary with Apache 2.0 binaries together.
Instead we are distributing VPNkit with performance penalty. (And VPNkit binary is not available on non-amd64)

Switching to slirp4netns is good, but not a blocker
