### ISSUE TITLE
[roadmap] Support TLS1.3

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#40495]
Tracking issue to track support for TLS1.3, now that Go supports it out of the box

related

- [x] https://github.com/docker/go-connections/pull/68 Add TLS 1.3 to list of TLS versions
- [x] review list of cyphers for TLS 1.3 (?)
- [ ] revendor go-connections https://github.com/moby/moby/pull/41042
- [ ] (tag, and) revendor docker/go-connections

**Comment by thaJeztah** [comment]
From the Golang docs: https://golang.org/doc/go1.12#tls_1_3

> TLS 1.3 cipher suites are not configurable. All supported cipher suites are safe, and if PreferServerCipherSuites is set in Config the preference order is based on the available hardware.

**Comment by AkihiroSuda** [comment]
What's the next step?

**Comment by SamWhited** [comment]
@thaJeztah I can pin this to master and update, but would we rather do a release of go-connections so that we have a tag to reference in the vendor.conf comment? If so, somebody with permissions on that repo will need to push a v0.5.0 tag or something.

**Comment by thaJeztah** [comment]
Good point; I added a note to the board; https://github.com/moby/moby/projects/9, Should we add a `go.mod` to that repository ? I think it'd be ok to temporarily use master, and we can vendor a tag before GA

**Comment by SamWhited** [comment]
Sounds good to me (docker/go-connections#69)

**Comment by AkihiroSuda** [comment]
@thaJeztah @tiborvass Can we move this to 21.XX milestone?
