### ISSUE TITLE
Remove (or reduce) dependency on runc libcontainer dependency

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#42452]
The runc maintainers have indicated that the `libcontainer` package is not intended for external consumption, and because of that has an "unstable" API.

We should reduce our use of this dependency.

- [ ] `libcontainer/cgroups` Use the container/cgroups package (https://github.com/containerd/cgroups) instead of libcontainer/cgroups (where possible), e.g. see https://github.com/moby/moby/pull/42071#discussion_r585767248.
    - identify what functionality is provided by libcontainer/cgroups that is not provided by containerd/cgroups
- [ ] `libcontainer/configs` 
    - [x] device parts we need have moved into `libcontainer/devices`: https://github.com/moby/moby/pull/42143
    - [ ] still used by `libcontainer/cgroups`
 - [ ] `libcontainer/devices`
     - [ ] still used by `libcontainer/configs`
 - [ ] `libcontainer/utils`
     - [ ] still used by `libcontainer/cgroups`
- [x] `libcontainer/system` 
    - [x] removed through https://github.com/moby/moby/pull/47668
- [x] `libcontainer/devices` used for `oci.Device`, `oci.DevicesFromPath()`. Need to look what's needed (and if this can be replaced with code from containerd; https://github.com/moby/moby/pull/43055
- [x] `libcontainer/userns`
    - [x] used by `libcontainer/cgroups` https://github.com/opencontainers/runc/pull/4350
    - [x] partially addressed through; https://github.com/moby/moby/pull/48307, https://github.com/moby/moby/pull/48170
    - [x] removed through https://github.com/moby/moby/pull/47668
- [x] `libcontainer/nsenter` is not used, but vendored because it has c code
- [x] `libcontainer/user` Is still needed; perhaps this package should live elsewhere (also used by containerd);
    - [x]  https://github.com/moby/moby/pull/46711
    - [x] removed through https://github.com/moby/moby/pull/47668

**Comment by AkihiroSuda** [comment]
> libcontainer/user Is still needed; perhaps this package should live elsewhere (also used by containerd)

Can we move this to moby/sys?

cc @kolyshkin

**Comment by thaJeztah** [comment]
It looks like the only remaining part is now `libcontainer/cgroups` (but that brings in `libcontainer/userns` and `libcontainer/configs`, `libcontainer/devices`. The only uses are in daemon: `withCgroups()`, and for these utilities;

`GetInitCgroup` and `GetOwnCgroup` https://github.com/moby/moby/blob/84ba2558e2e3d689ce2521dad9b541ab6e331243/daemon/oci_linux.go#L902-L906

`FindCgroupMountpointAndRoot`: https://github.com/moby/moby/blob/84ba2558e2e3d689ce2521dad9b541ab6e331243/daemon/oci_linux.go#L919C20-L919C29

**Comment by thaJeztah** [comment]
OK; looks like `libcontainer/system` is back in https://github.com/moby/moby/pull/48425/files#r1741918581

**Comment by kolyshkin** [comment]
Regarding the switch from runc/libcontainer/cgroups to containerd/cgroups, two things that came to my mind:

1. We have a (very preliminary) plan to separate libcontainer out of runc. Some details [here](https://github.com/kubernetes/kubernetes/issues/128157#issuecomment-2427394891).

3. I just found out that `containerd/cgroups/v3/cgroup2` brings in a huge `cilium/ebpf` dependency (~25K LOC from the top of my head), which is not really needed (as long as moby don't manage cgroup devices directly -- which it doesn't). This is the same issue we had with runc/libcontainer/cgroups and it was fixed in runc-1.2.0 (runc PRs [#3452](https://github.com/opencontainers/runc/pull/3452), [#4248](https://github.com/opencontainers/runc/pull/4248)). I was hoping runc 1.2.0 bump would bring the same joy (or removing cilium/ebpf from vendor) to moby as it did to kubernetes, alas moby switched to containerd/cgroups.
