### ISSUE TITLE
Post-libnetwork integration tasks

### ISSUE THREAD

**Issue by thaJeztah** [moby/moby#42471]
Tracking issue for post-libnetwork integration tasks after https://github.com/moby/moby/pull/42262:

- [ ] update BuildKit to use the new import paths, and upstream changes from: https://github.com/moby/buildkit/compare/244e8cde...cpuguy83:update_libnetwork_import
- [ ] re-vendor BuildKit to remove the temporary fork
- [ ] update SwarmKit to use the new import paths https://github.com/docker/swarmkit/compare/5a5494a9a7b408b790533a5e4e1cb43ca1c32aad...cpuguy83:switch_libnetwork
- [ ] re-vendor SwarmKit to remove the temporary fork
- [ ] look into test-failures / flakiness after integration
- [ ] Address review comments from https://github.com/moby/moby/pull/42262
    - [ ] remove left-over files (circleci config, maintainers file, etc)
    - [ ] replace github.com/urfave/cli with spf13/cobra
    - [ ] replace mflags package with spf13/pflags
    - [ ] get rid of some of the `//nolint:gosec` comments (where possible)
- [ ] Review/migrate/close open pull requests in libnetwork
    - [ ] Write instructions on how to migrate pull requests from libnetwork to moby
    - [ ] Leave comments on existing PRs with instructions
    - [ ] Close pull requests that are no longer relevant
- [ ] Update docker/libnetwork repository description and readme to describe status (deprecated, moved)
- [ ] Archive the docker/libnetwork repository once we no longer need it
- [ ] TBD: discuss if we want to backport https://github.com/moby/moby/pull/42262 to the 20.10 branch, so that we don't have to maintain libnetwork changes in two locations
