### ISSUE TITLE
25 Release Tracking

### ISSUE THREAD

**Issue by neersighted** [moby/moby#45926]
This is a tracking issue for the 25.0 major release.

We've identified the following issues as blockers for the release, in no particular order:
* [ ] BuildKit 0.12 (@neersighted; @tonistiigi)
* [ ] RRO (recursive read only) (@thaJeztah, @AkihiroSuda)
  * [ ] https://github.com/docker/cli/pull/4316 
  * [ ] more issues?
* [ ] [CDI 0.6.0](github.com/container-orchestrated-devices/container-device-interface) (@elezar)
* [ ] Health start interval (@cpuguy83): https://github.com/moby/moby/issues/45897

The following issues are "soft" blockers/nice-to-have, but should not prevent a release:
* [ ] file capabilities in non-root containers (@neersighted): https://github.com/moby/moby/pull/45511
* [ ] OpenTelemetry (@cpugy83): https://github.com/moby/moby/pull/45652
* [ ] ContainerCreate with multiple networks (@akerouanton)
  * [ ] https://github.com/moby/moby/pull/45906
  * [ ] more issues?
* [ ] Better `overlay2` function checks (@neersighted): https://github.com/moby/moby/pull/45890
* [ ] `#define` strings for seccomp defaultErrnoRet (@tianon, @neersighted)

@moby/moby-maintainers, please edit this list and keep it updated as we get closer to the release.

**Comment by elezar** [comment]
I created https://github.com/moby/moby/pull/45933 and https://github.com/docker/cli/pull/4416 to bump the CDI dependencies after tagging the `v0.6.0` release upstream.
