### ISSUE TITLE
[epic] fix remaining failing tests with the containerd image store

### ISSUE THREAD

**Issue by rumpl** [moby/moby#46760]
### Description

We are nearly there, I wanted to create a tracking issue for the remaining integration tests that fail with the containerd integration enabled, hopefully this will help us. I have added PRs when there is one for a failing test, and comments on why a test fail when I know what's wrong. Everyone should feel free to update the list if I have missed anything.

We are so close

* [x] TestDiskUsage/empty _layer size reported as 0 instead of 4096_ https://github.com/moby/moby/pull/46570
* [x] TestDockerCLIBuildSuite
    * [x] TestBuildAddCurrentDirWithCache https://github.com/moby/moby/pull/46634
    * [x] TestBuildAddLocalAndRemoteFilesWithAndWithoutCache https://github.com/moby/moby/pull/46634
    * [x] TestBuildAddMultipleLocalFileWithAndWithoutCache https://github.com/moby/moby/pull/46634
    * [x] TestBuildAddRemoteFileMTime https://github.com/moby/moby/pull/46634
    * [x] TestBuildAddRemoteFileWithAndWithoutCache https://github.com/moby/moby/pull/46634
    * [x] TestBuildCacheFrom https://github.com/moby/moby/pull/46634
    * [x] TestBuildCacheFromEqualDiffIDsLength https://github.com/moby/moby/pull/46634
    * [x] TestBuildClearCmd https://github.com/moby/moby/pull/46907
    * [x] TestBuildCopyDirButNotFile https://github.com/moby/moby/pull/46634
    * [x] TestBuildCopyWildcard https://github.com/moby/moby/pull/46634
    * [x] TestBuildExposeOrder https://github.com/moby/moby/pull/46634
    * [x] TestBuildLabelsCache https://github.com/moby/moby/pull/46634
    * [x] TestBuildSameDockerfileWithAndWithoutCache https://github.com/moby/moby/pull/46634
    * [x] TestBuildShellUpdatesConfig https://github.com/moby/moby/pull/46634
    * [x] TestBuildTimeArgHistoryExclusions https://github.com/moby/moby/pull/46634
    * [x] TestBuildWithTabs https://github.com/moby/moby/pull/46634
    * [x] TestBuildWorkdirCmd https://github.com/moby/moby/pull/46634
* [x] TestDockerCLIPullSuite 
    * [x] TestPullWindowsImageFailsOnLinux https://github.com/moby/moby/pull/46517
* [x] TestDockerCLIRmiSuite
    * [x] TestRmiUntagHistoryLayer https://github.com/moby/moby/pull/46840
* [x] TestDockerDaemonSuite
    * [x] TestCleanupMountsAfterDaemonAndContainerKill https://github.com/moby/moby/pull/46770
* [x] TestDockerRegistryAuthTokenSuite
    * [x] TestPushMisconfiguredTokenServiceResponseError - https://github.com/moby/moby/pull/46865
    * [x] TestPushMisconfiguredTokenServiceResponseNoToken - https://github.com/moby/moby/pull/46865
    * [x] TestPushMisconfiguredTokenServiceResponseUnauthorized - https://github.com/moby/moby/pull/46865
    * [x] TestPushMisconfiguredTokenServiceResponseUnparsable - https://github.com/moby/moby/pull/46865
    * [x] TestPushTokenServiceUnauthResponse - https://github.com/moby/moby/pull/46865
* [x] TestDockerRegistrySuite
    * [x] TestCrossRepositoryLayerPush - (https://github.com/moby/moby/pull/46855)
    * [x] TestDeleteImageByIDOnlyPulledByDigest https://github.com/moby/moby/pull/46840
    * [x] TestDeleteImageWithDigestAndMultiRepoTag https://github.com/moby/moby/pull/46840
    * [x] TestDeleteImageWithDigestAndTag https://github.com/moby/moby/pull/46840
    * [x] TestInspectImageWithDigests https://github.com/moby/moby/pull/46819
    * [x] TestListDanglingImagesWithDigests https://github.com/moby/moby/pull/46856 / https://github.com/moby/moby/pull/46868
    * [x] TestListImagesWithDigests https://github.com/moby/moby/pull/46758 https://github.com/moby/moby/pull/46819
    * [x] TestPullByDigestNoFallback https://github.com/moby/moby/pull/46819
    * [x] TestPullManifestList https://github.com/moby/moby/pull/46759
    * [x] TestPushBadTag https://github.com/moby/moby/pull/46685
* [x] amd64.integration.build.TestBuildUserNamespaceValidateCapabilitiesAreV2 - https://github.com/moby/moby/pull/46972
* [x] amd64.integration.image.TestPruneDontDeleteUsedDangling https://github.com/moby/moby/pull/46896
* [x] amd64.integration.image.TestSaveCheckTimes https://github.com/moby/moby/pull/46848
* [x] docker-py
	* [x] test_build_squash tests.integration.api_build_test.BuildTest https://github.com/moby/moby/pull/46935
	* [x] test_build_with_cache_from tests.integration.api_build_test.BuildTest https://github.com/moby/moby/pull/46634
	* [x] test_commit tests.integration.api_image_test.CommitTest https://github.com/moby/moby/pull/46912
	* [x] test_commit_with_changes tests.integration.api_image_test.CommitTest  https://github.com/moby/moby/pull/46912
	* [x] test_prune_images tests.integration.api_image_test.PruneImagesTest https://github.com/moby/moby/pull/46911
	* [x] test_pull_with_sha tests.integration.models_images_test.ImageCollectionTest -  https://github.com/moby/moby/pull/46819
	* [x] test_save_and_load tests.integration.models_images_test.ImageCollectionTest  - skipped by https://github.com/moby/moby/pull/46965, will be fixed by https://github.com/moby/moby/pull/46978
	* [x] test_save_and_load_repo_name tests.integration.models_images_test.ImageCollectionTest - skipped by https://github.com/moby/moby/pull/46965, will be fixed by https://github.com/moby/moby/pull/46978

**Comment by rumpl** [comment]
I see 54 of 54 are done, let's close this one, we have another one for the windows failures
