### ISSUE TITLE
containerd integration: Platform selection

### ISSUE THREAD

**Issue by vvoland** [moby/moby#47680]
### Description

A draft tracking issue for containerd multiplatform image UX PRs

The general rule of platform selection is:
1. Commands without `--platform` should act on the "full" multi-platform image instead of a single platform from that image if possible. Commands that act on information purely based on image config, should default to any present platform, but prefer the one matching the daemon host platform.
2. If the above is not possible, the command should act on any present platform, but prefer the one matching the daemon host platform.
3. Otherwise, the command should error and force user to explicitly pass a specific platform that the operation should act on.

# docker push --platform=...

Pick a platform-specific manifest and push it instead of the whole multi-platform index.

- [x] Add CLI switch - https://github.com/docker/cli/pull/4984
- [x] Server implementation - https://github.com/moby/moby/pull/47679

# docker images --tree
Make `docker images` output multi-platform aware

- [x] Expose platform-specific subimages informations in the API endpoint - https://github.com/moby/moby/pull/47526
- [x] PoC on the CLI side - https://github.com/docker/cli/pull/4982
- [ ] Implement as `cli/command/formatter`

# docker convert (cancelled)

Create new docker images from the existing multi-platform images and filter their manifests.
In future this could also support other operations (like converting layer compression, etc).

NOTE: While `docker image create` could be a better name for this, `docker
create` is already an alias to `docker container create`.

- [ ] CLI implementation - https://github.com/docker/cli/pull/4983
- [ ] Server implementation - https://github.com/moby/moby/pull/47678

# docker inspect --platform=...
- [x] Expose platform-specific subimages informations in the API endpoint - https://github.com/moby/moby/pull/48264
- [x] Platform selection [server] - https://github.com/moby/moby/pull/49586
- [x] Add CLI switch - https://github.com/docker/cli/pull/5934

# docker rmi --platform=...

Remove content of the specified platform

- [x] Add CLI switch https://github.com/docker/cli/pull/6109
- [x] Server implementation https://github.com/moby/moby/pull/49982

# docker save --platform=...

Pick a platform-specific manifest and save it instead of the whole multi-platform index.

- [x] Add CLI switch https://github.com/docker/cli/pull/5331
- [x] Server implementation https://github.com/moby/moby/pull/48295

# docker load --platform=...

Load the image from the tarball (multi-platform index), but only import specified platform blobs.

- [x] Add CLI switch https://github.com/docker/cli/pull/5331
- [x] Server implementation https://github.com/moby/moby/pull/48295

# docker history --platform=...

Show history for the specified platform, otherwise will show the host platform, if host platform isn't available, it will pick any.

- [x] Add CLI switch https://github.com/docker/cli/pull/5331
- [x] Server implementation https://github.com/moby/moby/pull/48295

**Comment by thaJeztah** [comment]
Also related;

- https://github.com/moby/moby/issues/49994
