### ISSUE TITLE
[epic] IPv6 improvements for moby 28.0

### ISSUE THREAD

**Issue by robmry** [moby/moby#48814]
### Description

Tracking/linking issue for [changes related to IPv6](https://github.com/moby/moby/issues?q=label%3Aarea%2Fnetworking%2Fipv6%20milestone%3A28.0.0) currently intended for release in moby 28.0.0 ...

- [x] https://github.com/moby/moby/pull/48322
- [x] https://github.com/moby/moby/pull/48609
- [x] https://github.com/moby/moby/pull/48492
  - [x] https://github.com/moby/moby/pull/48511
- [x] https://github.com/moby/moby/pull/47406
- [x] https://github.com/moby/moby/pull/48319

IPv6 Only - networks with no IPv4 address allocation ...

- [x] https://github.com/moby/moby/pull/48271
  - [x] https://github.com/moby/moby/pull/48489
- [x] https://github.com/moby/moby/pull/48135
- [x] https://github.com/moby/moby/pull/48248
- [x] https://github.com/moby/moby/pull/48278
- [x] https://github.com/moby/moby/pull/48284
- [x] https://github.com/moby/moby/pull/48290
- [x] https://github.com/moby/moby/pull/48299
- [x] https://github.com/moby/moby/pull/48323
- [x] https://github.com/moby/moby/pull/48807
- [x] https://github.com/moby/moby/pull/48808
- [x] https://github.com/moby/moby/pull/48809
