### ISSUE TITLE
[epic] iptables and port publishing improvements for moby 28.0

### ISSUE THREAD

**Issue by robmry** [moby/moby#48815]
### Description

Tracking/linking issue for [changes related to `iptables`](https://github.com/moby/moby/issues?q=milestone%3A28.0.0%20label%3Aarea%2Fnetworking%2Ffirewalling) and port publishing, currently intended for release in moby 28.0.0.

In addition to functional improvements, this is an initial step towards native nftables support.

- [x] https://github.com/moby/moby/pull/48570
- [x] https://github.com/moby/moby/pull/48571
- [x] https://github.com/moby/moby/pull/48575
- [x] https://github.com/moby/moby/pull/48721
- [x] https://github.com/moby/moby/pull/48593
  -  Docs in master: https://github.com/moby/moby/blob/master/integration/network/bridge/iptablesdoc/index.md
- [x] https://github.com/moby/moby/pull/48724
- [x] https://github.com/moby/moby/pull/48594
- [x] https://github.com/moby/moby/pull/48596
- [x] https://github.com/moby/moby/pull/48597
- [x] https://github.com/moby/moby/pull/48640
- [x] https://github.com/moby/moby/pull/48641

**Comment by thaJeztah** [comment]
@robmry looks like this one is all done, correct?

**Comment by robmry** [comment]
Oh, yes - hurrah!
