### ISSUE TITLE
Security: make Docker safe in multi-tenant situations.

### ISSUE THREAD

**Issue by cyphar** [moby/moby#6324]
This is a meta issue, used to group together issues which work towards the following goal.

Currently, Docker is _completely_ unsafe in multitenant situations. Any user which can write to the `docker.sock` socket has full access to the **host** filesystem. This issue becomes even worse, considering the fact that several projects mount the Docker socket _inside_ Docker containers -- where an exploited container could break out of the Docker sandbox without any real restrictions.

This issue will track other issues which work toward the above goal of securing the Docker daemon in multi-tenant situations.
### Current issues
- [x] Filesystem safety.
  - [x] References to container resources shouldn't escape the container's `basefs`.
    - [x] #5619 (PR: #6000) (absolute symlinks and symlink path components copy host target).
    - [x] #5656 (garbage paths could resolve to path in host).
- [x] Container users aren't namespace'd.
  - [x] Container's root shouldn't be able to read/write/execute as the host's root.
    - [x] #2918 (PR: #4572) (container root is identical to host root -- volumes can be written and read from as host root inside container).
- [ ] Docker doesn't have _any_ ACL. Writing to `docker.sock` == `root`.
  - [x] Implement access control #15365
- [ ] Docker runs as root, which means that any bugs in Docker can cause much more damage than necessary. https://rootlesscontaine.rs/ is something I've been working on.

There are almost certainly more issues that I haven't thought of. Please add them if you know of any. This issue can _only_ be closed when the Docker daemon is far more secure in multi-tenant situations.

**Comment by termie** [comment]
-subscribe-

**Comment by rgbkrk** [comment]
How safe is using a non-root user in the container? Same as a non-root user on the host?

**Comment by tphyahoo** [comment]
Could this have label project/security added?

**Comment by tphyahoo** [comment]
Since I can't add labels myself, I commented on the issues that seemed to me most critical to improving security. These are probably all relevant to the current meta issue:

https://github.com/docker/docker/issues?q=commenter%3Atphyahoo+security

Perhaps an admin can follow up with proper labels for follow-up.

**Comment by bettiolo** [comment]
@mseri can you look into fixing this?

**Comment by thaJeztah** [comment]
This PR (and related issues) may be of interest  for those following this: https://github.com/docker/docker/pull/15365

**Comment by alexanderkjeldaas** [comment]
Some of the info here seems not to be up to date.  See for example https://github.com/docker/docker/blob/master/experimental/userns.md

**Comment by adamkdean** [comment]
What is the latest on the ACL front?

**Comment by thaJeztah** [comment]
ACL can be added through Authorization plugins; https://docs.docker.com/engine/extend/plugins_authorization/

**Comment by edward-of-clt** [comment]
- subscribe -

**Comment by vdemeester** [comment]
cc @endophage @n4ss

**Comment by AkihiroSuda** [comment]
We have rootless mode (https://docs.docker.com/engine/security/rootless/), it seems we can close this issue?
